### ISSUE TITLE
About p.setGravity

### ISSUE THREAD

**Issue by Li-zhuoran** [Healthcare-Robotics/assistive-gym#18]
```
 File "/home/dell/RL/assistive-gym/assistive_gym/envs/agents/agent.py", line 228, in set_gravity
    p.setGravity(ax, ay, az, body=self.body, physicsClientId=self.id)
TypeError: function takes at most 4 arguments (5 given)
```

Everything was normal before .
 After I modified the version of pybullet, the above error occurred .

《PyBullet Quickstart Guide》shows that setGravity only needs  4 arguments.But I do need to set different gravity for different agents .
So .... how to solve this problem

**Comment by Zackory** [comment]
You will want to install the custom version of PyBullet required for Assistive Gym.
https://github.com/Healthcare-Robotics/assistive-gym/blob/main/setup.py#L21
https://github.com/Zackory/bullet3
