### ISSUE TITLE
Action space for FeedingSawyer

### ISSUE THREAD

**Issue by gabriansa** [Healthcare-Robotics/assistive-gym#21]
Hello,

Does anyone know what the action space for the FeedingSawyer example environment is?

Thanks in advance

**Comment by Zackory** [comment]
The action space is defined here: https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/env.py#L46 
The actions are delta joint angles, in radians, and shown here: https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/env.py#L214
For the Sawyer, you can find the joint indices (from the URDF) that are controlled: https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/agents/sawyer.py#L8

**Comment by gabriansa** [comment]
Okay, I thought it could have been delta joint angles. Thanks so much for confirming.

I have another question. I am trying to train a model and then transfer the trained policy onto a real Sawyer robot. I am actually pretty close to achieving this and I guess it could be a great addition to this library.
So my question is (rather dumb but just to double-check) the dimensions of the Sawyer in the simulation are realistic correct?

Just to make sure that what I input to the Sawyer is correct.

**Comment by Zackory** [comment]
Yes, it is the Sawyer URDF, which comes from the original Sawyer robot definition.
