### ISSUE TITLE
Import Custom 3D Objects

### ISSUE THREAD

**Issue by gabriansa** [Healthcare-Robotics/assistive-gym#22]
Hello,

I was wondering if there is a way to import custom 3D objects. I created a simple table on Fusion 360 and exported it as .obj. I then used [object2urdf](https://github.com/harvard-microrobotics/object2urdf) to create the urdf file as well as the vhacd file however when I load this into the simulation it doesn't show up.

Any hints/ideas on how to do this? Thanks a lot

**Comment by Zackory** [comment]
You may want to check out these two examples for importing obj files into PyBullet:
https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/agents/furniture.py#L18
https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/agents/tool.py#L32

**Comment by JiahangWu** [comment]
Hi,
I tried to import a new type of robot. First I added the robot .urfd file in the corresponding path and initialized it. Then, I registered in the ```__init.py__```. But it still shows ```error: Cannot load URDF file```. Is there something I didn't notice? Do you have some ideas about this? Thanks!
