### ISSUE TITLE
Can't load "human" environments

### ISSUE THREAD

**Issue by escribano89** [Healthcare-Robotics/assistive-gym#24]
Hi, I'm unable to load the "human" environments using the provided Google Collab: https://colab.research.google.com/drive/1PAY5HnLKRB-TBsPaevRr6myMfpVt_yzF

_No registered env with id: ScratchItchPandaHuman-v1_

It happens with all `[task][robot]Human-v1` environments. Thanks!

**Comment by Zackory** [comment]
This seems to be an issue with Google Colab.
If you install Assistive Gym locally, it should work just fine.
Typically, we register envs into the gym interface by calling register(): https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/__init__.py
However, for the 'human' environments, we need to co-optimize two separate policies and that requires using an RLlib environment register function. https://github.com/Healthcare-Robotics/assistive-gym/blob/main/assistive_gym/envs/scratch_itch_envs.py#L44
For some reason, Google Colab is not calling this function correctly and registering the 'human' environments.
