### ISSUE TITLE
Hi, I can't train ppo on tutorial 

### ISSUE THREAD

**Issue by Kaito-Kido** [Healthcare-Robotics/assistive-gym#25]
![image](https://user-images.githubusercontent.com/62087110/163599857-bb2c08d3-7052-4c72-8fb5-42f061a43da7.png)

**Comment by Zackory** [comment]
Is this in Google Colab?
I believe Colab made some changes recently (such as switching Python versions), and Assistive Gym may not be working (but I haven't verified this).
