### ISSUE TITLE
Suggestion about the install_requires

### ISSUE THREAD

**Issue by GilgameshD** [Healthcare-Robotics/assistive-gym#8]
Since the tensorflow package updates very fast and does not have a good compatibility, it's better to fix the tf version in setup.py
In my case, the latest tf==2.3.0 will cause some error.

Thanks!

**Comment by Zackory** [comment]
Hi Wenhao! Thanks for catching this.

The current development v1.0 branch has this suggestion already implemented, with tf==1.14.0.
https://github.com/Healthcare-Robotics/assistive-gym/blob/v1.0/setup.py

I'll update this in the master branch as a quick fix until v1.0 goes live.
